version: '2'
services:
  panganudclient:
    build:
      context: .      
      dockerfile: Dockerfile
    restart: always
    image: panganudclient:1.001
    ports:
      - 7200:3000
    command: npm run start

